### PR TITLE
madej spanko 26.10.2022

### PR DESCRIPTION
**Pull request by jakubmanczak**

### CODE REVIEW

**Comment by datejer** [comment]
Almost 6MB seems like quite a lot 🤔 Did you think about compressing/downscaling it?
image

**Review by AdamSiekierski — APPROVED** [review]
LGTM

**Comment by AdamSiekierski** [comment]
@datejer gatsby does the image optimization :))

**Comment by datejer** [comment]
I know, still it might speed it up and conserve some space :)

**Comment by jakubmanczak** [comment]
Image weights vary from 40KB to 3 MBs, how low exactly should I go?

**Comment by datejer** [comment]
I think it's fine as it is now, put might be good to remember for later so that this repo doesn't weight gigabytes 😂

**Review by datejer — APPROVED** [review]

**Pull request merged**
